version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - aws cloudformation package --template-file ./src/api/samTemplate.yml --s3-bucket sohnserverlessbucket --output-template-file outputSamTemplate.yml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yml
    - src/api/config/devConfig.json
    - src/api/config/prodConfig.json
  discard-paths: yes
