version: 0.2
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file ./templates/samTemplate.yml --s3-bucket sohnserverlessbucket --output-template-file outputSamTemplate.yml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yml
