  Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../handlers
      Handler: preTrafficHook.handler
      Runtime: nodejs8.10
      FunctionName: 'CodeDeployHook_preTrafficHook'
      DeploymentPreference:
        Enabled: false
      Environment:
        Variables:
          CURRENT_VERSION: !Join [ ':' , [ !GetAtt HelloWorldFunc.Arn, 'prod'] ]
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource: 'arn:aws:codedeploy:*'
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
            Resource: '*'
