  Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'HelloWorldFunc'
      Handler: helloWorld.handler
      Runtime: nodejs8.10
      CodeUri: ../handlers
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: AllAtOnce
        Hooks:
          # Validation Lambda function run before traffic shift
          PreTraffic: !Ref PreTrafficLambdaFunction
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: GET
            RestApiId:
                Ref: HelloWorldAPI
