AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Hello World API Endpoint configured using Swagger specified inline and backed by a Lambda function with pre-traffic Lambda testing during deployment
Parameters:
  StageName:
    Type: String
Resources:
  HelloWorldAPI:
    Name: HelloWorldAPI
    Type: AWS::Serverless::Api
    Properties:
        StageName:
          Ref: StageName
        DefinitionBody:
            swagger: 2.0
            info:
              title: HelloWorldAPI
            paths:
              "/HelloWorld":
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${HelloWorldFunc.Arn}:prod/invocations
                  responses: {}

  HelloWorldFunc:
    'Fn::Transform':
      Name: 'AWS::Include'
      Parameters:
        Location:
          Fn::Sub:
            "s3://${S3Bucket}/yml-files/helloWorld/helloWorld.yml"
  PreTrafficLambdaFunction:
    'Fn::Transform':
      Name: 'AWS::Include'
      Parameters:
        Location:
          Fn::Sub:
            "s3://${S3Bucket}/yml-files/helloWorld/preTraffic.yml"

Outputs:
  APIEndpoint:
    Description: "API Prod stage endpoint"
    Value:
      Fn::Sub:
        "https://${HelloWorldAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
