AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World API
Resources:
  HelloWorldFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ../src
      AutoPublishAlias: Prod
      DeploymentPreference:
       Type: Canary10Percent10Minutes
      Events:
        MyServerlessAPI:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: GET
