AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World API
Resources:
  HelloWorldFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MyServerlessAPI:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: GET
