AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swagger specified inline and backed by a Lambda function with pre-traffic Lambda testing during deployment
Resources:
  HelloWorldAPI:
    Type: AWS::Serverless::Api
    Properties:
        StageName: v1
        DefinitionBody:
            swagger: 2.0
            info:
              title: HelloWorldAPI
            paths:
              "/HelloWorld":
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${HelloWorldFunc.Arn}:prod/invocations
                  responses: {}

  HelloWorldFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ../src
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        # Type: AllAtOnce
        Hooks:
          # Validation Lambda function run before traffic shift
          PreTraffic: !Ref PreTrafficLambdaFunction
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: GET
            RestApiId:
                Ref: HelloWorldAPI

  PreTrafficLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: preTrafficHook.handler
      Runtime: nodejs8.10
      FunctionName: 'CodeDeployHook_preTrafficHook'
      DeploymentPreference:
        Enabled: false
      Environment:
        Variables:
          CURRENT_VERSION: !Join [ ':' , [ !GetAtt HelloWorldFunc.Arn, 'prod'] ]
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource: 'arn:aws:codedeploy:*'
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
            Resource: '*'
