AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Hello World API Endpoint configured using Swagger specified inline and backed by a Lambda function with pre-traffic and post-traffic Lambda testing during deployment
Parameters:
  StageName:
    Type: String
Resources:

  HelloWorldAPI:
    Name: HelloWorldAPI
    Type: AWS::Serverless::Api
    Properties:
        StageName: !Ref StageName
        DefinitionBody:
            swagger: 2.0
            info:
              title: HelloWorldAPI
            paths:
              "/HelloWorld":
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${HelloWorldFunc.Arn}:prod/invocations
                  responses: {}


  HelloWorldFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'HelloWorldFunc'
      Handler: helloWorld.handler
      Runtime: nodejs8.10
      CodeUri: ./handlers
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Alarms:
          - !Ref 5xxAlarm
          - !Ref 4xxAlarm
          - !Ref LatencyAlarm
        Hooks:
          # Validation Lambda function run before traffic shift
          PreTraffic: !Ref PreTrafficLambdaFunction
          PostTraffic: !Ref PostTrafficLambdaFunction
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: get
            RestApiId: !Ref HelloWorldAPI

  PreTrafficLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: preTrafficHook.handler
      Runtime: nodejs8.10
      FunctionName: 'CodeDeployHook_preTrafficHook'
      DeploymentPreference:
        Enabled: false
      Environment:
        Variables:
          CURRENT_VERSION: !Join [ ':' , [ !GetAtt HelloWorldFunc.Arn, 'prod'] ]
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource: 'arn:aws:codedeploy:*'
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
            Resource: '*'
  PostTrafficLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: postTrafficHook.handler
      Runtime: nodejs8.10
      FunctionName: 'CodeDeployHook_postTrafficHook'
      DeploymentPreference:
        Enabled: false
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource: 'arn:aws:codedeploy:*'
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "s3:*"
            Resource: '*'

  #
  # Lambda Deployment - API Gateway alarms
  #
  5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: HelloWorldAPI
    Properties:
      AlarmDescription: 5xx alarm for api gateway
      Namespace: 'AWS/ApiGateway'
      MetricName: 5XXError
      Dimensions:
        - Name: ApiName
          Value: !Ref HelloWorldAPI
      Statistic: Sum
      Period: '60'
      EvaluationPeriods: '11'
      Threshold: '5'
      ComparisonOperator: GreaterThanOrEqualToThreshold
  4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: HelloWorldAPI
    Properties:
      AlarmDescription: 4xx alarm for api gateway
      Namespace: 'AWS/ApiGateway'
      MetricName: 4XXError
      Dimensions:
        - Name: ApiName
          Value: !Ref HelloWorldAPI
      Statistic: Sum
      Period: '60'
      EvaluationPeriods: '11'
      Threshold: '5'
      ComparisonOperator: GreaterThanOrEqualToThreshold
  LatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: HelloWorldAPI
    Properties:
      AlarmDescription: latency alarm for api gateway
      Namespace: 'AWS/ApiGateway'
      MetricName: Latency
      Dimensions:
        - Name: ApiName
          Value: !Ref HelloWorldAPI
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '11'
      Threshold: '25000'
      ComparisonOperator: GreaterThanOrEqualToThreshold


Outputs:
  APIEndpoint:
    Description: "API Prod stage endpoint"
    Value:
      Fn::Sub:
        "https://${HelloWorldAPI}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
